'use strict';
// CONTEXT_POLICY budgets (indicative, conservative). Chars unless noted.
module.exports = {
  TASK_BRIEF_CHARS: 2000,
  MAX_EVIDENCE_PER_STEP: 8000,
  METHOD_METADATA_CHARS: 3000,
  UPSTREAM_PAYLOAD_CHARS: 2000,
  SYNTHESIS_WORKING_CHARS: 16000,
  DEFAULT_TOP_K: 5,
  MAX_QUERIES_PER_STEP: 2,
  POLICY: 'READ_MINIMUM_NECESSARY_CONTEXT',
};
