'use strict';
// [ASTRA-11I] Positioning + Offer Intelligence Engine — public surface.
// DESIGN + DETERMINISTIC IMPLEMENTATION + ISOLATED OFFLINE BENCHMARKING. No LLM.
// No ASTRA-11I output may feed production routing or autonomous action.
module.exports = {
  positioningEvidence: require('./positioning_evidence'),
  positioningTerritory: require('./positioning_territory'),
  categoryFrame: require('./category_frame'),
  valueProposition: require('./value_proposition'),
  differentiation: require('./differentiation'),
  distinctiveness: require('./distinctiveness'),
  positioningFit: require('./positioning_fit'),
  offerArchitecture: require('./offer_architecture'),
  offerComponent: require('./offer_component'),
  benefitModel: require('./benefit_model'),
  mechanism: require('./mechanism'),
  proofStrategy: require('./proof_strategy'),
  riskReversal: require('./risk_reversal'),
  objectionMap: require('./objection_map'),
  pricing: require('./pricing'),
  packaging: require('./packaging'),
  urgencyScarcity: require('./urgency_scarcity'),
  offerSegmentFit: require('./offer_segment_fit'),
  offerJourneyFit: require('./offer_journey_fit'),
  competitorComparison: require('./competitor_comparison'),
  offerGap: require('./offer_gap'),
  offerOpportunity: require('./offer_opportunity'),
  messageFoundation: require('./message_foundation'),
  claimValidation: require('./claim_validation'),
  conflicts: require('./conflicts'),
  completion: require('./completion'),
  report: require('./report'),
  engine: require('./engine'),
  POSITIONING_OFFER_SCHEMA_VERSION: require('./positioning_evidence').POSITIONING_OFFER_SCHEMA_VERSION,
  UCDM_SCHEMA_VERSION: require('../schema/entities').SCHEMA_VERSION,
  VOC_SCHEMA_VERSION: require('../voc/utterance').VOC_SCHEMA_VERSION,
  CUSTOMER_MODEL_SCHEMA_VERSION: require('../customer_model/attribute_evidence').CUSTOMER_MODEL_SCHEMA_VERSION,
  JOURNEY_SCHEMA_VERSION: require('../journey/journey_observation').JOURNEY_SCHEMA_VERSION,
  COMPETITOR_SCHEMA_VERSION: require('../competitor/competitor_profile').COMPETITOR_SCHEMA_VERSION,
};
