'use strict';
// [ASTRA-11J] Funnel + Revenue Intelligence Engine — public surface.
// DESIGN + DETERMINISTIC IMPLEMENTATION + ISOLATED OFFLINE BENCHMARKING. No LLM.
// No ASTRA-11J output may feed production routing or autonomous action.
module.exports = {
  funnelModel: require('./funnel_model'),
  funnelObservation: require('./funnel_observation'),
  transitionMetrics: require('./transition_metrics'),
  dropoff: require('./dropoff'),
  scopeValidation: require('./scope_validation'),
  timeWindow: require('./time_window'),
  cohort: require('./cohort'),
  channel: require('./channel'),
  attribution: require('./attribution'),
  cost: require('./cost'),
  unitEconomics: require('./unit_economics'),
  revenue: require('./revenue'),
  margin: require('./margin'),
  ltv: require('./ltv'),
  payback: require('./payback'),
  roasMer: require('./roas_mer'),
  breakEven: require('./break_even'),
  salesPipeline: require('./sales_pipeline'),
  bookingFunnel: require('./booking_funnel'),
  commerceFunnel: require('./commerce_funnel'),
  retention: require('./retention'),
  internalBaseline: require('./internal_baseline'),
  delta: require('./delta'),
  bottleneck: require('./bottleneck'),
  revenueLeakage: require('./revenue_leakage'),
  diagnosis: require('./diagnosis'),
  priority: require('./priority'),
  completion: require('./completion'),
  report: require('./report'),
  engine: require('./engine'),
  FUNNEL_REVENUE_SCHEMA_VERSION: require('./funnel_model').FUNNEL_REVENUE_SCHEMA_VERSION,
  UCDM_SCHEMA_VERSION: require('../schema/entities').SCHEMA_VERSION,
  VOC_SCHEMA_VERSION: require('../voc/utterance').VOC_SCHEMA_VERSION,
  JOURNEY_SCHEMA_VERSION: require('../journey/journey_observation').JOURNEY_SCHEMA_VERSION,
  POSITIONING_OFFER_SCHEMA_VERSION: require('../positioning_offer/positioning_evidence').POSITIONING_OFFER_SCHEMA_VERSION,
  COMPETITOR_SCHEMA_VERSION: require('../competitor/competitor_profile').COMPETITOR_SCHEMA_VERSION,
};
