'use strict';
const assert = require('assert'); const fs = require('fs'); const path = require('path'); const crypto = require('crypto');
const openapi = require('../src/integration/openapi_builder'); const router = require('../src/integration/astra_tool_router');
const tests=[]; let pass=0,fail=0; function t(n,f){tests.push({n,f});}
const BASE='https://ftoxermwkfebmnrudiuu.supabase.co/functions/v1';
t('exact production OpenAPI server and four operationIds',()=>{const s=openapi.build('https://ftoxermwkfebmnrudiuu.supabase.co'); assert.equal(s.servers[0].url,'https://ftoxermwkfebmnrudiuu.supabase.co'); const ids=Object.values(s.paths).map(x=>x.post.operationId); assert.deepEqual(new Set(ids).size,4); assert(ids.includes('searchKnowledgeBase')&&ids.includes('runAstraCampaign360')&&ids.includes('runAstraCreativeDirector')&&ids.includes('runAstraCreativeGeneration'));});
t('production creative generation fails closed without live provider',async()=>{const env={ASTRA_GPT_API_KEYS:'test'}; const headers={authorization:'Bearer test'}; const cd=await router.route({tool:'runAstraCreativeDirector',body:{input:'Dental creative',mode:'SINGLE_CREATIVE',brand_constraints:{offer:'booking'},reference_assets:[],commands:[]},headers},{},env); const g=await router.route({tool:'runAstraCreativeGeneration',body:{creative_director_output:cd.body.creative_director_output,generation_mode:'SINGLE_GENERATION',reference_assets:[]},headers},{},env); assert.equal(g.body.status,'BLOCKED'); assert(!g.body.generated_assets||!g.body.generated_assets.length);});
t('deployed search rejects missing auth',async()=>{const r=await fetch(BASE+'/search-kb',{method:'POST',headers:{'content-type':'application/json'},body:'{"query":"SMP"}'}); assert.equal(r.status,401);});
t('deployed ASTRA gateway rejects missing auth',async()=>{const r=await fetch(BASE+'/astra-tools/campaign-360',{method:'POST',headers:{'content-type':'application/json'},body:'{"input":"test"}'}); assert.equal(r.status,401);});
t('deployed ASTRA gateway rejects malformed auth',async()=>{const r=await fetch(BASE+'/astra-tools/campaign-360',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer invalid-test-token'},body:'{"input":"test"}'}); assert.equal(r.status,401);});
t('deployed ASTRA gateway CORS preflight',async()=>{const r=await fetch(BASE+'/astra-tools/campaign-360',{method:'OPTIONS'}); assert.equal(r.status,204); assert.equal(r.headers.get('access-control-allow-origin'),'*');});
t('gateway source has no command or filesystem execution',()=>{const s=fs.readFileSync(path.join(__dirname,'../../supabase/functions/astra-tools/index.ts'),'utf8'); assert(!/Deno\.Command|child_process|readTextFile|writeTextFile/.test(s));});
t('search implementation still uses both canonical RPCs',()=>{const s=fs.readFileSync(path.join(__dirname,'../../supabase/functions/search-kb/index.ts'),'utf8'); assert(/match_kb_chunks/.test(s)&&/search_kb_text/.test(s));});
t('protected hashes unchanged',()=>{const b=JSON.parse(fs.readFileSync(path.join(__dirname,'../packaging_runtime/protection_validation.json'))).current_sha256; for(const [f,h] of Object.entries(b)){const a=crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../..',f))).digest('hex'); assert.equal(a,h,f);}});
t('no ASTRA-10 schema migration',()=>{assert(!fs.readdirSync(path.join(__dirname,'../../supabase/migrations')).some(x=>/astra_10|deployment_gpt/i.test(x)));});
(async()=>{for(const x of tests){try{await x.f();pass++;console.log('PASS',x.n)}catch(e){fail++;console.log('FAIL',x.n,'::',e.message)}}console.log(`ASTRA10_TEST_RESULT pass=${pass} fail=${fail}`);if(fail)process.exit(1)})();
