'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const router = require('../src/integration/astra_tool_router');
const responses = require('../src/integration/integration_response');
const openapi = require('../src/integration/openapi_builder');
const mockImage = require('../src/creative_generation/mock_image_provider');

const ENV = { ASTRA_GPT_API_KEYS: 'test-key', ASTRA_ALLOWED_PROJECT_IDS: 'project-owned' };
const HEADERS = { authorization: 'Bearer test-key', 'x-requester-id': 'test-user' };
const tests = []; let pass = 0, fail = 0;
function t(name, fn) { tests.push({ name, fn }); }
function campaign(status = 'COMPLETE', extras = {}) { return async input => Object.assign({ workflow_id: 'WF_TEST', workflow_state_status: status, node_outputs: status === 'COMPLETE' ? [{ work_unit_id: 'market_context' }] : [], selected_methods_by_node: { market_context: { primary_method: 'METHOD_SMP' } }, synthesis: status === 'COMPLETE' ? { deliverable: { '16_known_limitations': [], '17_current_research_required': [] } } : null, cost: { model_calls: 0 }, reason: status === 'COMPLETE' ? null : 'fixture', required_inputs: status === 'WAITING_FOR_INPUT' ? ['business_type'] : [] }, extras); }
async function call(tool, body, options = {}, headers = HEADERS, env = ENV) { return router.route({ tool, body, headers }, options, env); }

t('1 campaign COMPLETE contract', async () => { const r = await call('runAstraCampaign360', { input: 'Create a 360 dental clinic campaign with $500 daily budget and WhatsApp.' }, { campaignRuntime: campaign() }); assert.equal(r.statusCode, 200); assert.equal(r.body.status, 'COMPLETE'); assert(r.body.workflow_id && Array.isArray(r.body.completed_nodes)); });
t('2 creative director COMPLETE', async () => { const r = await call('runAstraCreativeDirector', { input: 'Dental clinic premium editorial creative', mode: 'CREATIVE_VARIANTS', brand_constraints: { offer: 'booking', channels: ['meta_feed'] }, reference_assets: [], commands: [] }); assert.equal(r.body.status, 'COMPLETE'); assert(r.body.creative_director_output && r.body.creative_qa); });
t('3 creative generation mock COMPLETE', async () => { const cd = await call('runAstraCreativeDirector', { input: 'Dental clinic premium editorial creative', mode: 'SINGLE_CREATIVE', brand_constraints: { offer: 'booking' }, reference_assets: [], commands: [] }); const r = await call('runAstraCreativeGeneration', { creative_director_output: cd.body.creative_director_output, generation_mode: 'SINGLE_GENERATION', reference_assets: [] }, { imageProvider: mockImage.makeProvider() }); assert.equal(r.body.status, 'COMPLETE'); assert(r.body.final_approved_asset); });
t('4 WAITING_FOR_INPUT preserved', async () => { const r = await call('runAstraCampaign360', { input: 'help' }, { campaignRuntime: campaign('WAITING_FOR_INPUT') }); assert.equal(r.body.status, 'WAITING_FOR_INPUT'); assert.deepEqual(r.body.required_inputs, ['business_type']); });
t('5 BLOCKED preserved', async () => { const r = await call('runAstraCampaign360', { input: 'campaign with missing evidence' }, { campaignRuntime: campaign('BLOCKED') }); assert.equal(r.body.status, 'BLOCKED'); });
t('6 FAILED preserved', async () => { const r = await call('runAstraCampaign360', { input: 'simulate failure' }, { campaignRuntime: campaign('FAILED') }); assert.equal(r.body.status, 'FAILED'); });
t('7 CURRENT_RESEARCH_REQUIRED preserved', async () => { const r = await call('runAstraCampaign360', { input: 'current Meta settings' }, { campaignRuntime: campaign('COMPLETE', { synthesis: { deliverable: { '16_known_limitations': [], '17_current_research_required': [{ item: 'current Meta settings', flag: 'CURRENT_RESEARCH_REQUIRED' }] } } }) }); assert.equal(r.body.current_research_required[0].flag, 'CURRENT_RESEARCH_REQUIRED'); });
t('8 unauthorized rejected', async () => { const r = await call('runAstraCampaign360', { input: 'campaign' }, { campaignRuntime: campaign() }, {}); assert.equal(r.statusCode, 401); assert.equal(r.body.error.code, 'UNAUTHORIZED'); });
t('9 forbidden project rejected without existence leak', async () => { const r = await call('runAstraCampaign360', { input: 'campaign', project_id: 'other-project' }, { campaignRuntime: campaign() }); assert.equal(r.statusCode, 403); assert.equal(r.body.error.message, 'Project access denied'); assert(!JSON.stringify(r.body).includes('other-project')); });
t('10 owned project accepted', async () => { const r = await call('runAstraCampaign360', { input: 'campaign', project_id: 'project-owned' }, { campaignRuntime: campaign() }); assert.equal(r.statusCode, 200); });
t('11 invalid input rejected', async () => { const r = await call('runAstraCampaign360', { input: '' }, { campaignRuntime: campaign() }); assert.equal(r.statusCode, 400); });
t('12 oversized input rejected', async () => { const r = await call('runAstraCampaign360', { input: 'x'.repeat(router.MAX_INPUT + 1) }, { campaignRuntime: campaign() }); assert.equal(r.statusCode, 422); });
t('13 enum validation', async () => { const r = await call('runAstraCreativeDirector', { input: 'x', mode: 'WRONG' }); assert.equal(r.statusCode, 400); });
t('14 OpenAPI 3.1 operationIds exact and unique', () => { const spec = openapi.build(); assert.equal(spec.openapi, '3.1.0'); const ids = Object.values(spec.paths).map(x => x.post.operationId); assert.deepEqual(ids.sort(), ['runAstraCampaign360', 'runAstraCreativeDirector', 'runAstraCreativeGeneration', 'searchKnowledgeBase'].sort()); assert.equal(new Set(ids).size, 4); });
t('15 OpenAPI error responses complete', () => { for (const p of Object.values(openapi.build().paths)) for (const c of [400,401,403,422,500,503]) assert(p.post.responses[c]); });
t('16 secret redaction recursive', () => { const x = responses.sanitize({ service_role_key: 'secret', nested: { authorization: 'Bearer abc.def', message: 'sk-secretvalue123' } }); assert(!JSON.stringify(x).includes('secretvalue')); assert(!JSON.stringify(x).includes('abc.def')); });
t('17 runtime error hides stack and secret', async () => { const r = await call('runAstraCampaign360', { input: 'campaign' }, { campaignRuntime: async () => { throw new Error('bad sk-secretvalue123'); } }); assert.equal(r.statusCode, 500); assert(!JSON.stringify(r.body).includes('secretvalue')); assert(!('stack' in r.body)); });
t('18 searchKnowledgeBase contract preserved', async () => { const r = await call('searchKnowledgeBase', { query: 'SMP', top_k: 5 }, { searchKnowledgeBase: async b => ({ results: [{ content: b.query, match_type: 'semantic' }] }) }); assert.equal(r.statusCode, 200); assert.equal(r.body.results[0].content, 'SMP'); });
t('19 persistence is metadata-only and sanitized', async () => { let row; await call('runAstraCampaign360', { input: 'campaign', project_id: 'project-owned' }, { campaignRuntime: campaign(), persistence: async x => { row = x; } }); assert(row.tool_name === 'runAstraCampaign360' && !('input' in row)); });
t('20 provider abstraction source remains configurable', () => { const source = fs.readFileSync(path.join(__dirname, '../src/runtime/runtime_config.js'), 'utf8'); assert(/openrouter/.test(source) && /lmstudio/.test(source)); });
t('21 Edge gateway has narrow allowlist and no shell/filesystem', () => { const source = fs.readFileSync(path.join(__dirname, '../../supabase/functions/astra-tools/index.ts'), 'utf8'); assert(/campaign-360/.test(source) && /creative-director/.test(source) && /creative-generation/.test(source)); assert(!/child_process|Deno\.Command|readTextFile|writeTextFile/.test(source)); });
t('22 search Edge regression has bounds and sanitized errors', () => { const source = fs.readFileSync(path.join(__dirname, '../../supabase/functions/search-kb/index.ts'), 'utf8'); assert(/match_kb_chunks/.test(source) && /search_kb_text/.test(source)); assert(/query\.length > 12_000/.test(source)); assert(!/String\(err\)/.test(source)); });
t('23 protected hashes match ASTRA-07 baseline', () => { const baseline = JSON.parse(fs.readFileSync(path.join(__dirname, '../packaging_runtime/protection_validation.json'))).current_sha256; for (const [file, expected] of Object.entries(baseline)) { const actual = crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname, '../..', file))).digest('hex'); assert.equal(actual, expected, file); } });
t('24 no schema migration added for ASTRA-09', () => { const files = fs.readdirSync(path.join(__dirname, '../../supabase/migrations')); assert(!files.some(x => /astra|gpt/i.test(x))); });
t('25 production creative generation never defaults to mock', async () => { const cd = await call('runAstraCreativeDirector', { input: 'Dental creative', mode: 'SINGLE_CREATIVE', brand_constraints: { offer: 'booking' }, reference_assets: [], commands: [] }); const r = await call('runAstraCreativeGeneration', { creative_director_output: cd.body.creative_director_output, generation_mode: 'SINGLE_GENERATION', reference_assets: [] }); assert.equal(r.body.status, 'BLOCKED'); assert(!r.body.generated_assets || r.body.generated_assets.length === 0); });

(async () => { for (const x of tests) { try { await x.fn(); pass++; console.log('PASS', x.name); } catch (e) { fail++; console.log('FAIL', x.name, '::', e.message); } } console.log(`ASTRA09_TEST_RESULT pass=${pass} fail=${fail}`); if (fail) process.exit(1); })();
